# Generated by Django 4.2.1 on 2023-05-29 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(9999999999)],
            ),
        ),
    ]
