# Generated by Django 4.2.1 on 2023-05-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0002_user_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
