# Generated by Django 4.2.1 on 2023-05-31 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0007_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Singer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("licenar", "Licenar"), ("singer", "Singer")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="singer_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify.singer"
            ),
        ),
    ]
