# Generated by Django 4.2.1 on 2023-06-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0008_singer_alter_user_role_alter_song_singer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("licenar", "licenar"), ("singer", "singer")],
                max_length=10,
                null=True,
            ),
        ),
    ]
