# Generated by Django 4.2.1 on 2023-06-05 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0009_song_is_deleted_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="favorited_by",
            field=models.ManyToManyField(
                related_name="favorite_songs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
