# Generated by Django 4.2.1 on 2023-06-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0011_remove_song_favorited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
