# Generated by Django 4.2.1 on 2023-06-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0013_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="song",
            new_name="songs",
        ),
    ]
