# Generated by Django 4.2.1 on 2023-06-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0014_rename_song_favorite_songs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="is_favorite",
        ),
    ]
