# Generated by Django 4.2.1 on 2023-06-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0015_remove_song_is_favorite"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favorite",
            new_name="Favourite",
        ),
    ]
